version: '3.8'

services:
  docker_php:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: docker_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:80"

  docker_mysql:
      image: mysql:8.0
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: huss4321

  dicker_phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1