version: '3.8'

services:
  dockerphp:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dockerphp
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:80"
